version: '3'
services:
  app:
    build: .
    command: bash -c "(bundle check || bundle install) && rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - bundle:/bundle
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
volumes:
  bundle:
